# Generated by Django 4.2.8 on 2025-04-09 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('content_type', models.CharField(choices=[('news', 'News'), ('event', 'Event'), ('course_info', 'Course Information'), ('policy', 'University Policy'), ('faq', 'FAQ'), ('other', 'Other')], max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('last_scraped', models.DateTimeField(blank=True, null=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_sources', to='core.university')),
            ],
            options={
                'unique_together': {('university', 'url')},
            },
        ),
        migrations.CreateModel(
            name='ContentProcessingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('items_processed', models.IntegerField(default=0)),
                ('items_added', models.IntegerField(default=0)),
                ('items_updated', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='content.contentsource')),
            ],
        ),
        migrations.CreateModel(
            name='ScrapedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('summary', models.TextField(blank=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('content_type', models.CharField(choices=[('news', 'News'), ('event', 'Event'), ('course_info', 'Course Information'), ('policy', 'University Policy'), ('faq', 'FAQ'), ('other', 'Other')], max_length=20)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='content.contentsource')),
            ],
            options={
                'ordering': ['-published_date', '-scraped_at'],
                'unique_together': {('url', 'source')},
            },
        ),
    ]
