# Generated by Django 4.2.8 on 2025-04-28 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapedcontent',
            name='event_date_display',
            field=models.CharField(blank=True, help_text='Formatted date display', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scrapedcontent',
            name='event_day',
            field=models.CharField(blank=True, help_text="Day of the event (e.g., '28')", max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='scrapedcontent',
            name='event_end_time',
            field=models.CharField(blank=True, help_text="End time (e.g., '18:15')", max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='scrapedcontent',
            name='event_month',
            field=models.CharField(blank=True, help_text="Month of the event (e.g., 'APR')", max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='scrapedcontent',
            name='event_start_time',
            field=models.CharField(blank=True, help_text="Start time (e.g., '17:30')", max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='scrapedcontent',
            name='event_year',
            field=models.CharField(blank=True, help_text="Year of the event (e.g., '2025')", max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='scrapedcontent',
            name='location',
            field=models.CharField(blank=True, help_text='Event location', max_length=255, null=True),
        ),
    ]
