# Generated by Django 4.2.8 on 2025-04-18 07:27

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', core.models.CustomUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='temp_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
