# Generated by Django 4.2.8 on 2025-04-18 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_managers_user_temp_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='temp_email',
        ),
    ]
